# -*- coding: utf-8 -*-
"""Gerador de desculpas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rU5yL1O42FeRKHWLg1DvXvfCSJzVyQvM
"""

!pip install google-genai

import os
from google.colab import userdata
from google.genai import types
from google import genai

os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')
model = 'models/gemini-2.0-flash'
client = genai.Client()

chat_config = types.GenerateContentConfig(system_instruction='O usuário descreve a situação em que precisa de uma desculpa, e você gera algumas opções com diferentes níveis de seriedade ou humor (fornecidos também pelo usuário).')

prompt = input('Precisa se safar? Chegou no lugar certo! \nSou seu GERADOR DE DESCULPAS CRIATIVAS! \n\
Me conta seu perrengue e o nível de seriedade e humor que deseja usar em sua desculpa! \nCaso se sinta satisfeito com a desculpa fornecida por mim, basta digitar \"Obrigado\" no prompt e eu serei desligado! \n\
Sem julgamentos, só soluções (e boas risadas)! \n')

while prompt != 'Obrigado':
  response = chat.send_message(prompt)
  print('Aqui está uma sugestão de desculpas: ', response.text)
  print('\n\n')
  prompt = input('Está satisfeito? Caso contrário, me forneça mais detalhes: \n')

